### ISSUE TITLE
Result display "MQTT User" two times instead of "MQTT Passwort"

### ISSUE THREAD

**Issue by Lyve1981** [energychain/site_ecoflow_mqtt_credentials#1]
https://github.com/energychain/site_ecoflow_mqtt_credentials/blob/9e370ded7ff911b879fa159d191a02086a126a8b/assets/js/app.js#L46

This line should probably contain "Password" instead of "User"

**Comment by zoernert** [comment]
You are right. Do you like to create a PR?
