### ISSUE TITLE
Programmausgabe hat fehlerhafte Bezeichnung

### ISSUE THREAD

**Issue by AKGitH** [energychain/site_ecoflow_mqtt_credentials#2]
Die Programmausgabe hat eine fehlerhafte Bezeichnung. Das Password-Feld wird als "MQTT User" bezeichnet.
Es sollte beispielsweise in "MQTT User PW" geändert werden.

![image](https://github.com/user-attachments/assets/f0290202-e183-4feb-a8ed-9f104e838872)

**Comment by zoernert** [comment]
Please check latest fix. It should solve this issue.

AKGitH ***@***.***> schrieb am Di., 20. Aug. 2024, 21:34:

**Comment by AKGitH** [comment]
Now, it`s working.
![image](https://github.com/user-attachments/assets/860ab731-02af-435d-b1fb-372b2d65ae21)

**Comment by AKGitH** [comment]
Fixed.
